### ISSUE TITLE
OpenAI gum TypeError: object.__init__() takes no parameters

### ISSUE THREAD

**Issue by MonaTanggg** [kh-kim/stock_market_reinforcement_learning#11]
I got this error when I run

`python3 market_pg.py ./kospi_10.csv pg.h5`

```
Traceback (most recent call last):
  File "market_pg.py", line 147, in <module>
    env = MarketEnv(dir_path = "./data/", target_codes = list(codeMap.keys()), input_codes = [], start_date = "2010-08-25", end_date = "2015-08-25", sudden_death = -1.0)
  File "/home/mona/stock_market_reinforcement_learning-master/market_env.py", line 69, in __init__
    self.action_space = spaces.Discrete(len(self.actions))
  File "/home/mona/gym-master/gym/spaces/discrete.py", line 13, in __init__
    gym.Space.__init__(self, (), np.int64)
TypeError: object.__init__() takes no parameters
```

Is it my openAI version problem ?

**Comment by kakoedlinnoe** [comment]
python 3.6, gym 0.3.0 works perfectly
