### ISSUE TITLE
ImportError: No module named deeplearning_assistant.model_builder

### ISSUE THREAD

**Issue by jinpengchina** [kh-kim/stock_market_reinforcement_learning#6]
python market_pg.py ./kospi_10.csv pg.h5
Traceback (most recent call last):
  File "market_pg.py", line 5, in <module>
    from market_model_builder import MarketPolicyGradientModelBuilder
  File "/Users/tonylibai/code/python_ai/gym/stock_market_reinforcement_learning/market_model_builder.py", line 1, in <module>
    from deeplearning_assistant.model_builder import AbstractModelBuilder
ImportError: No module named deeplearning_assistant.model_builder

why ???

ImportError: No module named deeplearning_assistant.model_builder

**Comment by guoguo657** [comment]
Ｉ　ｈａｖｅ　ｍｅｔ　ｗｉｔｈ　ｔｈｅ　ｓａｍｅ　ｑｕｅｓｔｉｏｎ！　Ａｓｋ　ｆｏｒ　ｈｅｌｐ！

**Comment by hmingkwan** [comment]
I encountered the same problem, anyone can help?

**Comment by TheGU** [comment]
Clone this repo https://github.com/clxdsjyx/deeplearning_assistant to your repo should help.

**Comment by lemon57** [comment]
downloaded deeplearning_assistant directory to project directory, still doesn't work
try to run python market_pg.py or python market_pg.py ./kospi_10.csv pg.h5
The issue is the same: ImportError: No module named deeplearning_assistant.model_builder

What am I doing wrong?

**Comment by jorddenn** [comment]
The file to be imported is in the deeplearning_assistant repo that was linked above by @TheGU. The code is trying to use the model_builder.py file included in that repo. However the repo includes the file needed but the import statement is wrong, just delete the "deeplearning_assistant" part leaving only "model_builder", no need to download the extra repo
